import pandas as pd


class CollectorMixin:
    def daily_prices(code: str, date_range: pd.DatetimeIndex, **kwargs):
        '''
        code: the stock code
        date_range: the data's date range, generated by pandas.date_range(...)
        '''
        pass